//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gadgeteer.ServiceBusDirect
{
    
    public partial class Resource1
    {
        public static System.Resources.ResourceManager manager;
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource1.manager == null))
                {
                    Resource1.manager = new System.Resources.ResourceManager("Gadgeteer.ServiceBusDirect.Resource1", typeof(Resource1).Assembly);
                }
                return Resource1.manager;
            }
        }
        public static string GetString(Resource1.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        public static byte[] GetBytes(Resource1.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        public enum StringResources : short
        {
            Soap = -30610,
        }
        [System.SerializableAttribute()]
        public enum BinaryResources : short
        {
            VerisignCA = -25106,
        }
    }
}
